import type { TopicKey } from '@/lib/supabase';

export type DiagnosticQuestion = {
  id: string;
  topic: TopicKey;
  level: 1 | 2 | 3;
  question: string;
  options: string[];
  correctIndex: number;
};

export const DIAGNOSTIC_QUESTIONS_BY_GRADE: Record<'junior' | 'middle' | 'senior', DiagnosticQuestion[]> = {
  junior: [
    {
      id: 'j-p1',
      topic: 'percentages',
      level: 1,
      question: 'Найдите 10% от 200.',
      options: ['20', '2', '200', '10'],
      correctIndex: 0,
    },
    {
      id: 'j-p2',
      topic: 'percentages',
      level: 2,
      question: 'Товар стоил 500 рублей. Скидка 20%. Сколько стоит товар со скидкой?',
      options: ['400', '100', '480', '250'],
      correctIndex: 0,
    },
    {
      id: 'j-f1',
      topic: 'fractions',
      level: 1,
      question: 'Вычислите: 1/4 + 1/4',
      options: ['1/2', '1/8', '2/8', '1/16'],
      correctIndex: 0,
    },
    {
      id: 'j-f2',
      topic: 'fractions',
      level: 2,
      question: 'Вычислите: 2/3 × 4/5',
      options: ['8/15', '6/8', '8/12', '10/15'],
      correctIndex: 0,
    },
    {
      id: 'j-e1',
      topic: 'equations',
      level: 1,
      question: 'Решите уравнение: x + 7 = 12',
      options: ['x = 5', 'x = 19', 'x = 7', 'x = 12'],
      correctIndex: 0,
    },
    {
      id: 'j-e2',
      topic: 'equations',
      level: 2,
      question: 'Решите уравнение: 3x − 5 = 10',
      options: ['x = 5', 'x = 15', 'x = 3', 'x = 10'],
      correctIndex: 0,
    },
    {
      id: 'j-fn1',
      topic: 'functions',
      level: 1,
      question: 'Чему равно значение функции y = 2x + 3 при x = 4?',
      options: ['11', '7', '10', '14'],
      correctIndex: 0,
    },
    {
      id: 'j-fn2',
      topic: 'functions',
      level: 2,
      question: 'Функция y = 3x − 1. При каком x значение y равно 14?',
      options: ['x = 5', 'x = 3', 'x = 15', 'x = 7'],
      correctIndex: 0,
    },
  ],
  middle: [
    {
      id: 'm-p1',
      topic: 'percentages',
      level: 1,
      question: 'Найдите 20% от 150.',
      options: ['20', '30', '25', '15'],
      correctIndex: 1,
    },
    {
      id: 'm-p2',
      topic: 'percentages',
      level: 2,
      question: 'Цена товара повысилась на 10%, а затем на 20%. На сколько процентов выросла цена всего?',
      options: ['30%', '32%', '28%', '22%'],
      correctIndex: 1,
    },
    {
      id: 'm-p3',
      topic: 'percentages',
      level: 3,
      question: 'Число увеличили на 25%. На сколько процентов надо уменьшить полученное число, чтобы вернуться к исходному?',
      options: ['20%', '25%', '15%', '10%'],
      correctIndex: 0,
    },
    {
      id: 'm-f1',
      topic: 'fractions',
      level: 1,
      question: 'Вычислите: 1/2 + 1/3',
      options: ['2/5', '5/6', '1/6', '2/3'],
      correctIndex: 1,
    },
    {
      id: 'm-f2',
      topic: 'fractions',
      level: 2,
      question: 'Упростите: (3/4) × (8/9)',
      options: ['2/3', '24/36', '1/3', '3/2'],
      correctIndex: 0,
    },
    {
      id: 'm-f3',
      topic: 'fractions',
      level: 3,
      question: 'Решите: 1/(1+1/2)',
      options: ['3/2', '2/3', '1/3', '1/2'],
      correctIndex: 1,
    },
    {
      id: 'm-e1',
      topic: 'equations',
      level: 1,
      question: 'Решите уравнение: 2x + 5 = 11',
      options: ['x = 3', 'x = 8', 'x = 6', 'x = 2'],
      correctIndex: 0,
    },
    {
      id: 'm-e2',
      topic: 'equations',
      level: 2,
      question: 'Решите: 3(x − 2) = 2x + 1',
      options: ['x = 7', 'x = 5', 'x = 3', 'x = 1'],
      correctIndex: 0,
    },
    {
      id: 'm-e3',
      topic: 'equations',
      level: 3,
      question: 'При каком значении a уравнение 2x + a = 7 не имеет решений ни при каком x? (рассмотрите как параметр)',
      options: ['Такого a не существует', 'a = 7', 'a = 0', 'a = 3.5'],
      correctIndex: 0,
    },
    {
      id: 'm-fn1',
      topic: 'functions',
      level: 1,
      question: 'Чему равно значение функции y = 3x − 2 при x = 4?',
      options: ['10', '14', '12', '6'],
      correctIndex: 0,
    },
    {
      id: 'm-fn2',
      topic: 'functions',
      level: 2,
      question: 'Найдите нули функции y = x² − 9.',
      options: ['x = ±3', 'x = 3', 'x = 9', 'нулей нет'],
      correctIndex: 0,
    },
    {
      id: 'm-fn3',
      topic: 'functions',
      level: 3,
      question: 'Функция y = 2x² − 4x. При каком x достигается минимум?',
      options: ['x = 1', 'x = 2', 'x = 0', 'x = −1'],
      correctIndex: 0,
    },
  ],
  senior: [
    {
      id: 's-p1',
      topic: 'percentages',
      level: 2,
      question: 'Вкладчик положил в банк 500 000 тенге под 8% годовых с капитализацией процентов. Какая сумма будет на счёте через 2 года?',
      options: ['583 200 тг', '580 000 тг', '540 000 тг', '582 000 тг'],
      correctIndex: 0,
    },
    {
      id: 's-p2',
      topic: 'percentages',
      level: 3,
      question: 'Цена товара сначала повысилась на 25%, а затем новую цену снизили на 20%. На сколько процентов изменилась цена по сравнению с первоначальной?',
      options: ['Повысилась на 0%', 'Повысилась на 5%', 'Снизилась на 5%', 'Не изменилась'],
      correctIndex: 0,
    },
    {
      id: 's-f1',
      topic: 'fractions',
      level: 3,
      question: 'Найдите значение выражения: (2^(1/2) × 2^(1/3)) / 2^(1/6)',
      options: ['2', '2^(1/2)', '2^(2/3)', '4'],
      correctIndex: 0,
    },
    {
      id: 's-f2',
      topic: 'fractions',
      level: 3,
      question: 'Решите уравнение: log₂(x) + log₂(x-2) = 3',
      options: ['x = 4', 'x = 2', 'x = 8', 'x = -2'],
      correctIndex: 0,
    },
    {
      id: 's-e1',
      topic: 'equations',
      level: 3,
      question: 'Решите уравнение: (x² - 4) / (x - 2) = 0. Укажите все допустимые решения.',
      options: ['x = -2', 'x = 2', 'x = ±2', 'Нет решений'],
      correctIndex: 0,
    },
    {
      id: 's-e2',
      topic: 'equations',
      level: 3,
      question: 'При каких значениях параметра a уравнение x² + (a-1)x + a = 0 имеет два различных действительных корня?',
      options: ['a ∈ (0; 5) \ {1}', 'a ∈ ℝ', 'a > 0', 'a < 5'],
      correctIndex: 0,
    },
    {
      id: 's-se1',
      topic: 'systems_of_equations',
      level: 3,
      question: 'Решите систему: { x² + y² = 25, x + y = 7 }. Найдите сумму всех решений для x.',
      options: ['7', '5', '12', '14'],
      correctIndex: 0,
    },
    {
      id: 's-se2',
      topic: 'systems_of_equations',
      level: 3,
      question: 'Система уравнений { 2x - 3y = 1, 4x - 6y = 2 } имеет:',
      options: ['Бесконечно много решений', 'Одно решение', 'Не имеет решений', 'Два решения'],
      correctIndex: 0,
    },
    {
      id: 's-qe1',
      topic: 'quadratic_equations',
      level: 3,
      question: 'Найдите сумму кубов корней уравнения x² - 7x + 10 = 0 (без непосредственного нахождения корней).',
      options: ['133', '63', '35', '70'],
      correctIndex: 0,
    },
    {
      id: 's-qe2',
      topic: 'quadratic_equations',
      level: 3,
      question: 'При каком значении p уравнение x⁴ - 5x² + p = 0 имеет ровно два различных действительных корня?',
      options: ['p < 0 или p = 25/4', 'p = 0', 'p > 0', 'p = 5'],
      correctIndex: 0,
    },
    {
      id: 's-fn1',
      topic: 'functions',
      level: 3,
      question: 'Найдите производную функции f(x) = x³·ln(x) в точке x = 1.',
      options: ['1', '0', '3', 'e'],
      correctIndex: 0,
    },
    {
      id: 's-fn2',
      topic: 'functions',
      level: 3,
      question: 'Найдите область определения функции f(x) = √(4 - x²) + 1/(x - 1).',
      options: ['[-2; 1) ∪ (1; 2]', '[-2; 2]', 'ℝ \ {1}', '(−∞; 2]'],
      correctIndex: 0,
    },
  ],
};

export function getDiagnosticQuestions(grade: number): DiagnosticQuestion[] {
  if (grade <= 8) return DIAGNOSTIC_QUESTIONS_BY_GRADE.junior;
  if (grade <= 10) return DIAGNOSTIC_QUESTIONS_BY_GRADE.middle;
  return DIAGNOSTIC_QUESTIONS_BY_GRADE.senior;
}
