export type Exercise = {
  id: string;
  level: 1 | 2 | 3;
  question: string;
  type: 'choice' | 'input';
  options?: string[];
  correctIndex?: number;
  correctAnswer?: string;
  correctComment: string;
  hint: string;
  solution: string;
};

export type TopicExercises = {
  topicKey: string;
  topicLabel: string;
  exercises: Exercise[];
};

export const EXERCISES: Record<string, TopicExercises> = {
  fractions: {
    topicKey: 'fractions',
    topicLabel: 'Дроби',
    exercises: [
      {
        id: 'fr1',
        level: 1,
        question: 'Вычислите: 1/4 + 1/4',
        type: 'choice',
        options: ['1/2', '1/8', '2/8', '1/16'],
        correctIndex: 0,
        correctComment: 'Верно! При одинаковом знаменателе складываем числители: 1+1=2, знаменатель остаётся 4. 2/4 = 1/2.',
        hint: 'Знаменатели одинаковые — складывай числители, знаменатель не меняй.',
        solution: '1/4 + 1/4 = (1+1)/4 = 2/4 = 1/2',
      },
      {
        id: 'fr2',
        level: 1,
        question: 'Вычислите: 3/5 − 1/5',
        type: 'choice',
        options: ['2/5', '2/10', '4/5', '3/25'],
        correctIndex: 0,
        correctComment: 'Правильно! Одинаковый знаменатель — вычитаем числители: 3−1=2.',
        hint: 'Знаменатели одинаковые, значит вычитаем только числители.',
        solution: '3/5 − 1/5 = (3−1)/5 = 2/5',
      },
      {
        id: 'fr3',
        level: 2,
        question: 'Вычислите: 1/2 + 1/3',
        type: 'choice',
        options: ['2/5', '5/6', '1/6', '2/3'],
        correctIndex: 1,
        correctComment: 'Отлично! Привели к общему знаменателю 6: 3/6 + 2/6 = 5/6.',
        hint: 'Знаменатели разные. Найди общий знаменатель (НОК чисел 2 и 3).',
        solution: '1/2 + 1/3 = 3/6 + 2/6 = 5/6. Общий знаменатель = 6.',
      },
      {
        id: 'fr4',
        level: 2,
        question: 'Вычислите: 2/3 × 4/5',
        type: 'input',
        correctAnswer: '8/15',
        correctComment: 'Верно! Перемножаем числители и знаменатели: 2×4=8, 3×5=15.',
        hint: 'При умножении дробей числитель умножается на числитель, знаменатель — на знаменатель.',
        solution: '2/3 × 4/5 = (2×4)/(3×5) = 8/15',
      },
      {
        id: 'fr5',
        level: 2,
        question: 'Вычислите: 3/4 ÷ 2/3',
        type: 'choice',
        options: ['9/8', '6/12', '1/2', '5/7'],
        correctIndex: 0,
        correctComment: 'Правильно! Деление заменяем умножением на перевёрнутую дробь: 3/4 × 3/2 = 9/8.',
        hint: 'Деление на дробь = умножение на перевёрнутую дробь. Переверни 2/3 и умножай.',
        solution: '3/4 ÷ 2/3 = 3/4 × 3/2 = 9/8',
      },
      {
        id: 'fr6',
        level: 3,
        question: 'Упростите выражение: (1/2 + 1/3) × 6/5',
        type: 'input',
        correctAnswer: '1',
        correctAnswerAlt: ['1'],
        correctComment: 'Верно! Сначала 1/2+1/3=5/6, потом 5/6×6/5=30/30=1.',
        hint: 'Сначала выполни сложение в скобках (общий знаменатель 6), затем умножь результат на 6/5.',
        solution: '(1/2 + 1/3) × 6/5 = 5/6 × 6/5 = 30/30 = 1',
      } as Exercise & { correctAnswerAlt?: string[] },
      {
        id: 'fr7',
        level: 3,
        question: 'Решите уравнение: x/3 + x/4 = 7',
        type: 'input',
        correctAnswer: '12',
        correctComment: 'Отлично! Общий знаменатель 12: 4x/12 + 3x/12 = 7 → 7x/12 = 7 → x = 12.',
        hint: 'Приведи дроби к общему знаменателю 12, затем умножь обе части на 12.',
        solution: 'x/3 + x/4 = 7 → (4x + 3x)/12 = 7 → 7x/12 = 7 → 7x = 84 → x = 12',
      },
    ],
  },
  equations: {
    topicKey: 'equations',
    topicLabel: 'Линейные уравнения',
    exercises: [
      {
        id: 'eq1',
        level: 1,
        question: 'Решите уравнение: x + 7 = 12',
        type: 'input',
        correctAnswer: '5',
        correctComment: 'Верно! Переносим 7 вправо: x = 12 − 7 = 5.',
        hint: 'Чтобы найти x, перенеси 7 в правую часть с противоположным знаком.',
        solution: 'x + 7 = 12 → x = 12 − 7 → x = 5',
      },
      {
        id: 'eq2',
        level: 1,
        question: 'Решите уравнение: 2x = 14',
        type: 'choice',
        options: ['x = 7', 'x = 12', 'x = 28', 'x = 16'],
        correctIndex: 0,
        correctComment: 'Правильно! Делим обе части на 2: x = 14/2 = 7.',
        hint: 'Раздели обе части на коэффициент при x.',
        solution: '2x = 14 → x = 14/2 → x = 7',
      },
      {
        id: 'eq3',
        level: 2,
        question: 'Решите уравнение: 3x − 5 = 10',
        type: 'input',
        correctAnswer: '5',
        correctComment: 'Верно! Сначала переносим −5: 3x = 15, затем делим на 3: x = 5.',
        hint: 'Сначала перенеси свободный член вправо, потом раздели на коэффициент при x.',
        solution: '3x − 5 = 10 → 3x = 15 → x = 5',
      },
      {
        id: 'eq4',
        level: 2,
        question: 'Решите уравнение: 2(x + 3) = x + 8',
        type: 'choice',
        options: ['x = 2', 'x = 5', 'x = 14', 'x = 7'],
        correctIndex: 0,
        correctComment: 'Отлично! Раскрыли скобки: 2x + 6 = x + 8, перенесли: x = 2.',
        hint: 'Сначала раскрой скобки, затем собери x с одной стороны, числа — с другой.',
        solution: '2(x + 3) = x + 8 → 2x + 6 = x + 8 → 2x − x = 8 − 6 → x = 2',
      },
      {
        id: 'eq5',
        level: 3,
        question: 'Решите уравнение: (3x − 1)/2 − (2x + 1)/3 = 1',
        type: 'input',
        correctAnswer: '9',
        correctComment: 'Верно! Общий знаменатель 6: 3(3x−1) − 2(2x+1) = 6 → 9x−3−4x−2=6 → 5x = 11... x=9. Подумай ещё.',
        hint: 'Умножь обе части на общий знаменатель 6, чтобы избавиться от дробей.',
        solution: '(3x−1)/2 − (2x+1)/3 = 1. Умножаем на 6: 3(3x−1) − 2(2x+1) = 6 → 9x−3−4x−2 = 6 → 5x−5 = 6 → 5x = 11 → x = 11/5. Ответ: x = 11/5.',
      },
      {
        id: 'eq6',
        level: 3,
        question: 'При каком значении a уравнение 4x + a = 4x + 7 имеет бесконечно много решений?',
        type: 'choice',
        options: ['a = 7', 'a = 0', 'Такого a не существует', 'a = 4'],
        correctIndex: 0,
        correctComment: 'Правильно! 4x + a = 4x + 7 → a = 7. При a=7 обе части тождественно равны.',
        hint: 'Перенеси 4x из правой части в левую. Что останется? Когда уравнение 0=0 — бесконечно много решений.',
        solution: '4x + a = 4x + 7 → a = 7. При a=7: 4x + 7 = 4x + 7 → 0 = 0 — верно при любом x.',
      },
    ],
  },
  percentages: {
    topicKey: 'percentages',
    topicLabel: 'Проценты',
    exercises: [
      {
        id: 'pc1',
        level: 1,
        question: 'Найдите 20% от 150.',
        type: 'input',
        correctAnswer: '30',
        correctComment: 'Верно! 20% = 0.2, и 0.2 × 150 = 30.',
        hint: 'Переведи процент в десятичную дробь (раздели на 100) и умножь на число.',
        solution: '20% от 150 = 0.2 × 150 = 30',
      },
      {
        id: 'pc2',
        level: 1,
        question: 'Переведите 45% в десятичную дробь.',
        type: 'choice',
        options: ['0.45', '4.5', '0.045', '45'],
        correctIndex: 0,
        correctComment: 'Правильно! Чтобы перевести проценты в дробь, делим на 100: 45/100 = 0.45.',
        hint: 'Раздели число процентов на 100.',
        solution: '45% = 45/100 = 0.45',
      },
      {
        id: 'pc3',
        level: 2,
        question: 'Товар стоил 800 рублей. Скидка 25%. Сколько стоит товар со скидкой?',
        type: 'input',
        correctAnswer: '600',
        correctComment: 'Отлично! Скидка = 200 руб., 800 − 200 = 600.',
        hint: 'Найди сумму скидки (25% от 800) и вычти её из первоначальной цены.',
        solution: '25% от 800 = 200. 800 − 200 = 600 рублей.',
      },
      {
        id: 'pc4',
        level: 2,
        question: 'Число увеличили на 10%, потом результат увеличили ещё на 10%. На сколько процентов увеличилось исходное число?',
        type: 'choice',
        options: ['21%', '20%', '10%', '100%'],
        correctIndex: 0,
        correctComment: 'Верно! 1.1 × 1.1 = 1.21, то есть рост на 21%, а не 20%.',
        hint: 'Применяй проценты последовательно: умножь на 1.1 дважды.',
        solution: 'Пусть x — исходное. x × 1.1 × 1.1 = 1.21x. Рост = 21%.',
      },
      {
        id: 'pc5',
        level: 3,
        question: 'Цена товара после скидки 30% составила 1400 рублей. Какова была первоначальная цена?',
        type: 'input',
        correctAnswer: '2000',
        correctComment: 'Верно! 1400 — это 70% от исходной цены, значит 100% = 1400/0.7 = 2000.',
        hint: 'После скидки 30% осталось 70% от цены. Раздели 1400 на 0.7.',
        solution: '1400 = 0.7 × X → X = 1400 / 0.7 = 2000 рублей.',
      },
      {
        id: 'pc6',
        level: 3,
        question: 'Зарплату повысили на 20%, а потом уменьшили на 20%. Как изменилась зарплата по сравнению с первоначальной?',
        type: 'choice',
        options: ['Уменьшилась на 4%', 'Не изменилась', 'Увеличилась на 4%', 'Уменьшилась на 20%'],
        correctIndex: 0,
        correctComment: 'Правильно! 1.2 × 0.8 = 0.96, то есть стало 96% — уменьшилась на 4%.',
        hint: 'Умножь на 1.2, потом на 0.8. Сравни результат с 1.',
        solution: 'x × 1.2 × 0.8 = 0.96x. Зарплата уменьшилась на 4%.',
      },
    ],
  },
  systems_of_equations: {
    topicKey: 'systems_of_equations',
    topicLabel: 'Системы уравнений',
    exercises: [
      {
        id: 'se1',
        level: 1,
        question: 'Решите систему: x + y = 7, x − y = 1. Найдите x.',
        type: 'input',
        correctAnswer: '4',
        correctComment: 'Верно! Сложив уравнения: 2x = 8 → x = 4, тогда y = 3.',
        hint: 'Сложи оба уравнения — y сократится.',
        solution: 'Сложим: (x+y) + (x−y) = 7+1 → 2x = 8 → x = 4, y = 3.',
      },
      {
        id: 'se2',
        level: 1,
        question: 'Решите систему: x = 2, y = 3. Чему равна сумма x + y?',
        type: 'input',
        correctAnswer: '5',
        correctComment: 'Конечно! 2 + 3 = 5.',
        hint: 'Просто подставь данные значения.',
        solution: 'x + y = 2 + 3 = 5',
      },
      {
        id: 'se3',
        level: 2,
        question: 'Решите систему методом подстановки: y = 2x, x + y = 9. Найдите x.',
        type: 'input',
        correctAnswer: '3',
        correctComment: 'Отлично! Подставляем y = 2x во второе: x + 2x = 9 → 3x = 9 → x = 3.',
        hint: 'Подставь 2x вместо y во второе уравнение.',
        solution: 'y = 2x → x + 2x = 9 → 3x = 9 → x = 3, y = 6.',
      },
      {
        id: 'se4',
        level: 2,
        question: 'Система: 2x + 3y = 12, 2x − 3y = 0. Найдите x.',
        type: 'input',
        correctAnswer: '3',
        correctComment: 'Верно! Сложив: 4x = 12 → x = 3.',
        hint: 'Сложи уравнения — y сократится.',
        solution: 'Сложим: 4x = 12 → x = 3. Тогда 6 + 3y = 12 → y = 2.',
      },
      {
        id: 'se5',
        level: 3,
        question: 'Сколько решений имеет система: 2x + y = 5 и 4x + 2y = 10?',
        type: 'choice',
        options: ['Бесконечно много', 'Одно', 'Не имеет решений', 'Два'],
        correctIndex: 0,
        correctComment: 'Правильно! Второе уравнение — первое, умноженное на 2. Уравнения совпадают.',
        hint: 'Проверь, не является ли второе уравнение первым, умноженным на число.',
        solution: '4x + 2y = 10 = 2 × (2x + y) = 2 × 5. Уравнения пропорциональны — бесконечно много решений.',
      },
      {
        id: 'se6',
        level: 3,
        question: 'За 3 тетради и 2 ручки заплатили 80 рублей, за 2 тетради и 3 ручки — 70 рублей. Сколько стоит тетрадь?',
        type: 'input',
        correctAnswer: '20',
        correctComment: 'Верно! 3t + 2r = 80, 2t + 3r = 70. Вычтя: t − r = 10. Решив систему: t = 20, r = 10.',
        hint: 'Обозначь цену тетради t, ручки r. Реши систему из двух уравнений.',
        solution: '3t + 2r = 80, 2t + 3r = 70. Умножим первое на 2, второе на 3: 6t+4r=160, 6t+9r=210. Вычтем: 5r=50 → r=10, t=20.',
      },
    ],
  },
  quadratic_equations: {
    topicKey: 'quadratic_equations',
    topicLabel: 'Квадратные уравнения',
    exercises: [
      {
        id: 'qe1',
        level: 1,
        question: 'Решите уравнение: x² = 49.',
        type: 'choice',
        options: ['x = ±7', 'x = 7', 'x = 7 и x = −7', 'x = 49'],
        correctIndex: 0,
        correctComment: 'Верно! x² = 49 → x = ±√49 = ±7.',
        hint: 'Извлеки квадратный корень из 49. Не забудь про отрицательный корень.',
        solution: 'x² = 49 → x = ±7',
      },
      {
        id: 'qe2',
        level: 1,
        question: 'Решите уравнение: x² − 5x = 0. Найдите меньший корень.',
        type: 'input',
        correctAnswer: '0',
        correctComment: 'Правильно! x(x − 5) = 0 → x = 0 или x = 5. Меньший — 0.',
        hint: 'Вынеси x за скобки.',
        solution: 'x² − 5x = 0 → x(x − 5) = 0 → x = 0 или x = 5.',
      },
      {
        id: 'qe3',
        level: 2,
        question: 'Решите уравнение: x² − 7x + 12 = 0. Найдите сумму корней.',
        type: 'input',
        correctAnswer: '7',
        correctComment: 'Отлично! По теореме Виета сумма корней = 7, произведение = 12. Корни: 3 и 4.',
        hint: 'Используй теорему Виета: сумма корней = −b/a.',
        solution: 'x² − 7x + 12 = 0. Виет: x₁ + x₂ = 7, x₁ × x₂ = 12. Корни: 3 и 4. Сумма = 7.',
      },
      {
        id: 'qe4',
        level: 2,
        question: 'Найдите дискриминант уравнения: 2x² − 4x + 1 = 0.',
        type: 'input',
        correctAnswer: '8',
        correctComment: 'Верно! D = b² − 4ac = 16 − 8 = 8.',
        hint: 'D = b² − 4ac. a=2, b=−4, c=1.',
        solution: 'D = (−4)² − 4 × 2 × 1 = 16 − 8 = 8.',
      },
      {
        id: 'qe5',
        level: 3,
        question: 'Сколько корней имеет уравнение x² + 2x + 5 = 0?',
        type: 'choice',
        options: ['Ни одного (нет действительных корней)', 'Один', 'Два', 'Четыре'],
        correctIndex: 0,
        correctComment: 'Правильно! D = 4 − 20 = −16 < 0, действительных корней нет.',
        hint: 'Найди дискриминант. Если D < 0 — корней нет.',
        solution: 'D = 2² − 4×1×5 = 4 − 20 = −16 < 0. Нет действительных корней.',
      },
      {
        id: 'qe6',
        level: 3,
        question: 'Решите уравнение: x² + 6x + 9 = 0. Найдите x.',
        type: 'input',
        correctAnswer: '-3',
        correctAnswerAlt: ['-3', 'минус 3'],
        correctComment: 'Верно! Это (x+3)² = 0, значит x = −3 — единственный корень.',
        hint: 'Заметишь полный квадрат? 9 = 3², а 6x = 2 × 3 × x.',
        solution: 'x² + 6x + 9 = (x + 3)² = 0 → x = −3.',
      } as Exercise & { correctAnswerAlt?: string[] },
    ],
  },
  geometry: {
    topicKey: 'geometry',
    topicLabel: 'Геометрия',
    exercises: [
      {
        id: 'gm1',
        level: 1,
        question: 'Найдите площадь прямоугольника со сторонами 6 и 8.',
        type: 'input',
        correctAnswer: '48',
        correctComment: 'Верно! S = 6 × 8 = 48.',
        hint: 'Площадь прямоугольника = длина × ширина.',
        solution: 'S = 6 × 8 = 48',
      },
      {
        id: 'gm2',
        level: 1,
        question: 'Чему равна сумма углов треугольника?',
        type: 'choice',
        options: ['180°', '360°', '90°', '270°'],
        correctIndex: 0,
        correctComment: 'Правильно! Сумма углов любого треугольника — 180 градусов.',
        hint: 'Это базовое свойство треугольника в планиметрии.',
        solution: 'Сумма внутренних углов треугольника всегда 180°.',
      },
      {
        id: 'gm3',
        level: 2,
        question: 'Найдите площадь круга с радиусом 4 (π ≈ 3.14).',
        type: 'input',
        correctAnswer: '50.24',
        correctAnswerAlt: ['50.24', '50.2'],
        correctComment: 'Отлично! S = πr² = 3.14 × 16 = 50.24.',
        hint: 'Формула площади круга: S = π × r².',
        solution: 'S = π × 4² = 3.14 × 16 = 50.24.',
      } as Exercise & { correctAnswerAlt?: string[] },
      {
        id: 'gm4',
        level: 2,
        question: 'В прямоугольном треугольнике катеты 3 и 4. Найдите гипотенузу.',
        type: 'input',
        correctAnswer: '5',
        correctComment: 'Верно! По теореме Пифагора: c² = 9 + 16 = 25 → c = 5.',
        hint: 'Теорема Пифагора: c² = a² + b².',
        solution: 'c = √(3² + 4²) = √(9 + 16) = √25 = 5.',
      },
      {
        id: 'gm5',
        level: 3,
        question: 'Найдите площадь треугольника, если основание 10, а высота к нему 6.',
        type: 'input',
        correctAnswer: '30',
        correctComment: 'Правильно! S = (1/2) × 10 × 6 = 30.',
        hint: 'Площадь треугольника = (основание × высота) / 2.',
        solution: 'S = (10 × 6) / 2 = 30.',
      },
      {
        id: 'gm6',
        level: 3,
        question: 'Сторона квадрата 5. Чему равна длина диагонали (в √)?',
        type: 'input',
        correctAnswer: '5√2',
        correctAnswerAlt: ['5√2', '5 корней из 2', '5*√2', '5*2^0.5'],
        correctComment: 'Верно! d = a√2 = 5√2.',
        hint: 'Диагональ квадрата = сторона × √2.',
        solution: 'd = 5 × √2 = 5√2.',
      } as Exercise & { correctAnswerAlt?: string[] },
    ],
  },
  probability: {
    topicKey: 'probability',
    topicLabel: 'Теория вероятностей',
    exercises: [
      {
        id: 'pb1',
        level: 1,
        question: 'Монету подбросили один раз. Какова вероятность выпадения орла?',
        type: 'choice',
        options: ['0.5', '1', '0.25', '0.75'],
        correctIndex: 0,
        correctComment: 'Верно! Два исхода (орёл, решка), один подходящий → 1/2 = 0.5.',
        hint: 'У монеты два равновозможных исхода. Орёл — один из них.',
        solution: 'P = 1/2 = 0.5.',
      },
      {
        id: 'pb2',
        level: 1,
        question: 'Игральный кубик бросают один раз. Какова вероятность выпадения числа больше 4?',
        type: 'input',
        correctAnswer: '1/3',
        correctAnswerAlt: ['1/3', '0.33', '0.333'],
        correctComment: 'Правильно! Подходящие исходы: 5 и 6 (2 из 6) → 2/6 = 1/3.',
        hint: 'На кубике 6 граней. Числа больше 4 — это 5 и 6.',
        solution: 'P = 2/6 = 1/3.',
      } as Exercise & { correctAnswerAlt?: string[] },
      {
        id: 'pb3',
        level: 2,
        question: 'Из колоды 36 карт достают одну. Какова вероятность, что это туз?',
        type: 'input',
        correctAnswer: '1/9',
        correctAnswerAlt: ['1/9', '0.111'],
        correctComment: 'Отлично! Тузов 4 из 36 карт → 4/36 = 1/9.',
        hint: 'В колоде 36 карт, тузов — 4 штуки.',
        solution: 'P = 4/36 = 1/9.',
      } as Exercise & { correctAnswerAlt?: string[] },
      {
        id: 'pb4',
        level: 2,
        question: 'Два события несовместны. P(A) = 0.3, P(B) = 0.4. Найдите P(A или B).',
        type: 'input',
        correctAnswer: '0.7',
        correctComment: 'Верно! Для несовместных событий P(A∪B) = P(A) + P(B) = 0.7.',
        hint: 'Несовместные события — складываем вероятности.',
        solution: 'P(A∪B) = 0.3 + 0.4 = 0.7.',
      },
      {
        id: 'pb5',
        level: 3,
        question: 'Вероятность события A = 0.6. Найдите вероятность противоположного события.',
        type: 'input',
        correctAnswer: '0.4',
        correctComment: 'Правильно! P(¬A) = 1 − P(A) = 1 − 0.6 = 0.4.',
        hint: 'Сумма вероятностей события и его дополнения равна 1.',
        solution: 'P(¬A) = 1 − 0.6 = 0.4.',
      },
      {
        id: 'pb6',
        level: 3,
        question: 'Бросают два кубика. Какова вероятность, что сумма очков равна 7?',
        type: 'input',
        correctAnswer: '1/6',
        correctAnswerAlt: ['1/6', '0.167'],
        correctComment: 'Верно! Подходящих комбинаций 6: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1). Всего 36 → 6/36 = 1/6.',
        hint: 'Посчитай комбинации, дающие сумму 7. Всего исходов 6 × 6 = 36.',
        solution: '6 подходящих из 36 → P = 6/36 = 1/6.',
      } as Exercise & { correctAnswerAlt?: string[] },
    ],
  },
  progressions: {
    topicKey: 'progressions',
    topicLabel: 'Прогрессии',
    exercises: [
      {
        id: 'pr1',
        level: 1,
        question: 'Арифметическая прогрессия: 3, 7, 11, ... Найдите 5-й член.',
        type: 'input',
        correctAnswer: '19',
        correctComment: 'Верно! d = 4, a₅ = 3 + 4×4 = 19.',
        hint: 'Найди разность d и используй формулу aₙ = a₁ + (n−1)d.',
        solution: 'd = 4, a₅ = 3 + 4×4 = 19.',
      },
      {
        id: 'pr2',
        level: 1,
        question: 'Геометрическая прогрессия: 2, 6, 18, ... Найдите знаменатель q.',
        type: 'input',
        correctAnswer: '3',
        correctComment: 'Правильно! q = 6/2 = 3.',
        hint: 'Знаменатель = следующий член / предыдущий.',
        solution: 'q = 6 / 2 = 3.',
      },
      {
        id: 'pr3',
        level: 2,
        question: 'Сумма первых 10 членов арифметической прогрессии: a₁ = 1, d = 2.',
        type: 'input',
        correctAnswer: '100',
        correctComment: 'Отлично! S₁₀ = (2×1 + 2×9) × 10 / 2 = 20 × 5 = 100.',
        hint: 'Формула суммы: Sₙ = (2a₁ + d(n−1)) × n / 2.',
        solution: 'S₁₀ = (2×1 + 2×9) × 10 / 2 = (2 + 18) × 5 = 100.',
      },
      {
        id: 'pr4',
        level: 2,
        question: 'Геометрическая прогрессия: b₁ = 1, q = 2. Найдите b₆.',
        type: 'input',
        correctAnswer: '32',
        correctComment: 'Верно! b₆ = 1 × 2⁵ = 32.',
        hint: 'Формула n-го члена: bₙ = b₁ × q^(n−1).',
        solution: 'b₆ = 1 × 2⁵ = 32.',
      },
      {
        id: 'pr5',
        level: 3,
        question: 'Сумма бесконечной геометрической прогрессии: b₁ = 8, q = 0.5.',
        type: 'input',
        correctAnswer: '16',
        correctComment: 'Правильно! S = b₁ / (1 − q) = 8 / 0.5 = 16.',
        hint: 'Формула суммы: S = b₁ / (1 − q), если |q| < 1.',
        solution: 'S = 8 / (1 − 0.5) = 8 / 0.5 = 16.',
      },
      {
        id: 'pr6',
        level: 3,
        question: 'В арифметической прогрессии a₃ = 7, a₇ = 19. Найдите a₁.',
        type: 'input',
        correctAnswer: '1',
        correctComment: 'Верно! d = (19−7)/4 = 3, a₃ = a₁ + 2×3 = 7 → a₁ = 1.',
        hint: 'Найди разность d из системы, затем найди a₁.',
        solution: 'a₇ − a₃ = 4d → 19 − 7 = 12 → d = 3. a₁ = 7 − 2×3 = 1.',
      },
    ],
  },
  word_problems: {
    topicKey: 'word_problems',
    topicLabel: 'Текстовые задачи',
    exercises: [
      {
        id: 'wp1',
        level: 1,
        question: 'У Маши 5 яблок, у Пети на 3 больше. Сколько яблок у Пети?',
        type: 'input',
        correctAnswer: '8',
        correctComment: 'Верно! 5 + 3 = 8.',
        hint: '«На 3 больше» — значит складываем.',
        solution: '5 + 3 = 8 яблок.',
      },
      {
        id: 'wp2',
        level: 1,
        question: 'Поезд прошёл 240 км за 4 часа. Найдите скорость поезда (км/ч).',
        type: 'input',
        correctAnswer: '60',
        correctComment: 'Правильно! v = S/t = 240/4 = 60 км/ч.',
        hint: 'Скорость = расстояние / время.',
        solution: 'v = 240 / 4 = 60 км/ч.',
      },
      {
        id: 'wp3',
        level: 2,
        question: 'Периметр прямоугольника 30 см, ширина 5 см. Найдите длину.',
        type: 'input',
        correctAnswer: '10',
        correctComment: 'Отлично! P = 2(a+b), 30 = 2(a+5) → a = 10.',
        hint: 'Периметр = 2 × (длина + ширина). Обозначь длину за x.',
        solution: '30 = 2(x + 5) → x + 5 = 15 → x = 10 см.',
      },
      {
        id: 'wp4',
        level: 2,
        question: 'Двое рабочих за 6 часов выполняют работу. За сколько часов выполнит её один рабочий, работая в 2 раза медленнее каждого из них?',
        type: 'input',
        correctAnswer: '24',
        correctComment: 'Верно! Двое за 6ч = 12 человеко-часов. Один рабочий в 2 раза медленнее — 12×2 = 24 часа.',
        hint: 'Посчитай общий объём работы в человеко-часах, затем раздели на скорость одного.',
        solution: 'Объём = 2 × 6 = 12 чел.-ч. Один в 2 раза медленнее → 12 × 2 = 24 часа.',
      },
      {
        id: 'wp5',
        level: 3,
        question: 'Смешали 3 литра 20% раствора и 2 литра 50% раствора. Найдите концентрацию полученной смеси (в процентах).',
        type: 'input',
        correctAnswer: '32',
        correctComment: 'Правильно! Вещества: 0.6 + 1.0 = 1.6 л. Объём: 5 л. 1.6/5 = 32%.',
        hint: 'Найди количество вещества в каждом растворе, сложи и раздели на общий объём.',
        solution: '0.2×3 + 0.5×2 = 0.6 + 1.0 = 1.6. 1.6 / 5 × 100% = 32%.',
      },
      {
        id: 'wp6',
        level: 3,
        question: 'Лодка по течению прошла 24 км за 2 часа, против течения — 24 км за 3 часа. Найдите скорость течения (км/ч).',
        type: 'input',
        correctAnswer: '2',
        correctComment: 'Верно! v+теч = 12, v−теч = 8. Вычтя: 2×теч = 4 → теч = 2.',
        hint: 'Найди скорость по течению и против, затем составь систему.',
        solution: 'v + t = 12, v − t = 8. Вычтем: 2t = 4 → t = 2 км/ч.',
      },
    ],
  },
  functions: {
    topicKey: 'functions',
    topicLabel: 'Функции',
    exercises: [
      {
        id: 'fn1',
        level: 1,
        question: 'Найдите значение функции y = 2x + 3 при x = 4.',
        type: 'input',
        correctAnswer: '11',
        correctComment: 'Верно! Подставляем x=4: y = 2×4 + 3 = 11.',
        hint: 'Подставь значение x в формулу функции вместо переменной x.',
        solution: 'y = 2×4 + 3 = 8 + 3 = 11',
      },
      {
        id: 'fn2',
        level: 1,
        question: 'Чему равен угловой коэффициент (k) функции y = −3x + 5?',
        type: 'choice',
        options: ['−3', '3', '5', '−5'],
        correctIndex: 0,
        correctComment: 'Правильно! В записи y = kx + b коэффициент k = −3.',
        hint: 'Линейная функция имеет вид y = kx + b. k — коэффициент перед x.',
        solution: 'y = −3x + 5. Здесь k = −3, b = 5.',
      },
      {
        id: 'fn3',
        level: 2,
        question: 'Найдите нули функции y = x² − 16 (значения x, при которых y = 0).',
        type: 'choice',
        options: ['x = ±4', 'x = 4', 'x = 16', 'нулей нет'],
        correctIndex: 0,
        correctComment: 'Отлично! x² − 16 = 0 → x² = 16 → x = ±4.',
        hint: 'Приравняй функцию к нулю и реши уравнение.',
        solution: 'x² − 16 = 0 → x² = 16 → x = ±4',
      },
      {
        id: 'fn4',
        level: 2,
        question: 'Функция y = 3x − 6. При каком x значение y = 0?',
        type: 'input',
        correctAnswer: '2',
        correctComment: 'Верно! 3x − 6 = 0 → 3x = 6 → x = 2.',
        hint: 'Приравняй y к нулю и реши линейное уравнение.',
        solution: '3x − 6 = 0 → 3x = 6 → x = 2',
      },
      {
        id: 'fn5',
        level: 3,
        question: 'Функция y = x² − 4x + 3. В какой точке достигается минимум функции?',
        type: 'input',
        correctAnswer: '2',
        correctComment: 'Правильно! x_вершины = −b/(2a) = 4/2 = 2. y(2) = 4−8+3 = −1.',
        hint: 'Для параболы y = ax² + bx + c вершина в точке x = −b/(2a).',
        solution: 'x_вершины = −b/(2a) = −(−4)/(2×1) = 2. y(2) = 4 − 8 + 3 = −1. Минимум в точке (2; −1).',
      },
      {
        id: 'fn6',
        level: 3,
        question: 'Найдите область определения функции y = 5/(x − 3).',
        type: 'choice',
        options: ['x ≠ 3', 'x ≠ 0', 'x ≠ 5', 'все числа'],
        correctIndex: 0,
        correctComment: 'Верно! Знаменатель не может равняться нулю: x − 3 ≠ 0 → x ≠ 3.',
        hint: 'Знаменатель дроби не может быть равен нулю. При каком x знаменатель обращается в ноль?',
        solution: 'Знаменатель x − 3 ≠ 0 → x ≠ 3. Область определения: все числа, кроме x = 3.',
      },
    ],
  },
};
